### ISSUE TITLE
Typo module returns error when typo not detected

### ISSUE THREAD

**Issue by doorooful** [doorooful/CapstoneProject#129]
**Symptom:**
External API for our typo module is returning `HTML` when given sentence doesn't contain any wrong word.
The content includes message as:`기술적 한계로 찾지 못한 맞춤법 오류나 문법 오류가 있을 수 있습니다.` 

**AC:**
- Temporarily handle exception not to affect the whole program

**Screenshot:**
![image](https://github.com/doorooful/CapstoneProject/assets/110809138/b3dfd75b-1818-42d1-be3b-20a033fbb819)

**Comment by doorooful** [comment]
Expected returning:

```bash
(.venv) jeongdooroo@jeongdulus-MacBook-Pro typo % python run.py
---Typo module processing---
../../../database/test.txt
Reading from original contents ...
Fetching errors ...
response is 
 -------------------- <Response [200]>
data is 
 -------------------- {"str":"오탈자 잇슴.","errInfo":[{"help":"&apos;있습니다&apos;와 &apos;없습니다&apos;가 평서문의 종결 형태이므로 명사형을 만들 때 혼동하여 &apos;있슴&apos;, &apos;없슴&apos;으로 표기하는데 이는 잘못 입니다. 명사형으로 활용할 때는 각각의 기본형 &apos;있다&apos;와 &apos;없다&apos;의 어간 &apos;있-&apos;과 &apos;없-&apos;에 명사형 전성어미 &apos;-음&apos;이 결합하여 &apos;있음&apos;과 &apos;없음&apos;이 됩니다.","errorIdx":0,"correctMethod":2,"start":4,"errMsg":"","end":6,"orgStr":"잇슴","candWord":"있음"}],"idx":0}
Replacing errors ...
```

**Comment by doorooful** [comment]
Symptom:
``` bash
(.venv) jeongdooroo@jeongdulus-MacBook-Pro typo % python run.py
---Typo module processing---
../../../database/test.txt
Reading from original contents ...
Fetching errors ...
response is 
 -------------------- <Response [200]>
data is 
 -------------------- <!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
<link rel='stylesheet' type='text/css' href='css/speller.css'>
<link rel='stylesheet' type='text/css' href='css/redesign.css'>
<script type="text/javascript" src="js/jquery-3.3.1.min.js"></script>
<script type="text/javascript" src="js/speller.js"></script>
<title>한국어 맞춤법/문법 검사기</title>
</head>
<body leftmargin="0" topmargin="0" text="#333333" style="zoom: 1;">
        <table id="tableMain">
                <tbody>
                        <tr id="trMain">
                                <td id="tdHead"
                                        style="background-image: url('./images/title.gif');"><a
                                        href="javascript:void(0);" onclick="fShowHelpPopup('./');">온라인 검사기 사용법</a>
                                        &nbsp;|&nbsp; <a href="javascript:void(0);" onclick="fShowUserReportPopup('./');">의견
                                                보내기</a></td>
                        </tr>
                        <tr id="trMain">
                                <td id="tdBody" style="text-align: center;">맞춤법과 문법 오류를 찾지
                                        못했습니다.<br>
                                <br>기술적 한계로 찾지 못한 맞춤법 오류나 문법 오류가 있을 수 있습니다. <br>
                                <br>
                                <input id="btnGoBackEditor" type="image" tabindex="2" title="돌아가기"
                                        src="./images/btnGoBackEditor.gif"
                                        onmouseout="this.src='./images/btnGoBackEditor.gif';"
                                        onmouseover="this.src='./images/btnGoBackEditor_over.gif';"
                                        onmousedown="this.src='./images/btnGoBackEditor_click.gif';"
                                        onclick="history.back()">&nbsp;&nbsp;&nbsp;&nbsp;<input
                                        id="btnRenew2" type="image" tabindex="1" title="새 문서 검사하기"
                                        src="./images/btnRenew2.gif"
                                        onmouseout="this.src='./images/btnRenew2.gif';"
                                        onmouseover="this.src='./images/btnRenew2_over.gif';"
                                        onmousedown="this.src='./images/btnRenew2_click.gif';"
                                        onclick="fRenew()">
                                </td>
                        </tr>
                        <tr id="trMain">
                                <td id="tdTail">

                                        <table id="tableTail">
                                                <tbody>
                                                        <tr id="trMain">
                                                                <td id="tdLogo" rowspan="3"
                                                                        style="background-image: url('./images/logo.jpg');"></td>
                                                                <td id="tdCopyright">Copyrightⓒ2001 AI Lab &amp;
                                                                        Narainfotech. All Rights Reserved.</td>
                                                                <td id="tdTailMenu">
                                                                        <p style="margin-left: 90px;">
                                                                                <a href="javascript:void(0);" onclick="fShowOrderPopup(&quot;./&quot;);">맞춤법/문법 검사기 구매 문의<br>(MS Word/아래아 한글용)</a>
                                                                        </p>
                                                                </td>
                                                        </tr>
                                                        <tr id="trMain">
                                                                <td id="tdTailDesc" colspan="2">한국어 맞춤법/문법 검사기는 부산대학교
                                                                        인공지능연구실과 (주)나라인포테크가 공동으로 만들고 있습니다.</td>
                                                        </tr>
                                                        <tr id="trMain">
                                                                <td id="tdTailDesc" colspan="2">새 인터페이스는 <a
                                                                        href="http://pxd.co.kr/">pxd. inc.</a>의 <a
                                                                        href="http://story.pxd.co.kr/1096">無異</a>님께서 제공해주셨습니다.
                                                                </td>
                                                        </tr>
                                                </tbody>
                                        </table>
                                </td>
                        </tr>
                </tbody>
        </table>
        <div id='divPopupBackground'></div>
        <div id='divClosePopup'>
                <input id='btnClosePopup' type='button' value='이전 화면' ONCLICK='fHidePopup();' />
        </div>
        <img id='imgPopup' />
        <iframe id='framePopup' class='noScrolling'></iframe>
</body>
</html>
Traceback (most recent call last):
  File "/Users/jeongdooroo/doorooful/CapstoneProject/dt-demo-be/modules/typo/run.py", line 74, in <module>
    run("test.txt")
  File "/Users/jeongdooroo/doorooful/CapstoneProject/dt-demo-be/modules/typo/run.py", line 35, in run
    data_dict = json.loads(data)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```
